name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Add host key to known_hosts
        run: |
          # mkdir -p ~/.ssh
          # echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/SPCM.pem
          # chmod 600 ~/.ssh/SPCM.pem
          ssh-keyscan -H ec2-15-207-100-48.ap-south-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Connect to EC2 and Deploy
        run: |
          ssh -o StrictHostKeyChecking=yes ec2-user@ec2-15-207-100-48.ap-south-1.compute.amazonaws.com << 'EOF'
            echo "Pulling the latest Docker image..."
            docker pull ${{secrets.DOCKER_USERNAME}}/backend:latest

            echo "Stopping and removing old container..."
            docker stop backend || true
            docker rm backend

            echo "Running new container..."
            docker run -d --name backend -p 5000:5000 --env-file .env ${{ secrets.DOCKER_USERNAME }}/backend:latest

            echo "Deployment Completed!"
          EOF
